import "./globals.css";
import VideoBackground from "./Components/VideoBackground";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <VideoBackground />
        <div className="content-wrapper">{children}</div>
      </body>
    </html>
  );
}
